git:
  depth: 1

branches:
  only:
    - master

sudo: false

language: node_js

node_js:
  - "6"
  - "7"
  - "8"
  - "9"
  - "10"

cache:
  directories:
  - node_modules

before_script:
  - npm install -g grunt-cli
  - npm prune

script:
  - grunt
